[server]
enableCORS = true
[client]
enableFavicon = true

[global]
runOnSave = true

[theme]
primaryColor="#f63366"
backgroundColor="#000000"
secondaryBackgroundColor="#0a101a"
textColor="#ffffff"
font="Franklin Gothic Medium Cond"

[tool]
packages = "libgl1-mesa-glx"

[logger]
level = "info"
